"use client";
import {useState} from "react";
import {useWallet} from "../lib/genlayer/wallet";
import {confirmWrite} from "../lib/genlayer/transactions";
import {env,assertConfigured} from "../lib/config";

export function ProtocolActions({orgId}:{orgId:string}){
  const {address,writeClient,chainOk}=useWallet(); const [state,setState]=useState(""); const [busy,setBusy]=useState(false);
  const [source,setSource]=useState({label:"",url:"",purpose:"official_site"}); const [manifesto,setManifesto]=useState("");
  const run=async(functionName:string,args:unknown[])=>{if(busy)return;try{assertConfigured();if(!chainOk)throw new Error("WRONG_NETWORK: switch wallet to Studionet 61999");if(!address||!writeClient)throw new Error("Connect a wallet before signing.");setBusy(true);setState("AWAITING_SIGNATURE");await writeClient.connect("studionet");const hash=await writeClient.writeContract({address:env.coreAddress as `0x${string}`,functionName,args});setState(`CONSENSUS ${hash}`);const final=await confirmWrite(writeClient,hash,async()=>setState(`FINALIZED ${hash} / rereading Core`));setState(final.hash?`${final.stage} ${final.hash}`:final.stage)}catch(e){setState(e instanceof Error?e.message:"CONTRACT_ERROR")}finally{setBusy(false)}};
  return <div className="mt-10 border-t border-[#E9E1CF22] pt-6"><div className="grid gap-3 md:grid-cols-2"><input aria-label="source label" value={source.label} onChange={e=>setSource({...source,label:e.target.value})} placeholder="Source label" className="border-b border-[#E9E1CF44] bg-transparent p-3 text-xs"/><input aria-label="source URL" value={source.url} onChange={e=>setSource({...source,url:e.target.value})} placeholder="https://source.example/path" className="border-b border-[#E9E1CF44] bg-transparent p-3 text-xs"/><select aria-label="source purpose" value={source.purpose} onChange={e=>setSource({...source,purpose:e.target.value})} className="border border-[#E9E1CF22] bg-[#0B0B0A] p-3 text-xs"><option value="official_site">official_site</option><option value="repo">repo</option><option value="governance">governance</option><option value="activity_feed">activity_feed</option></select><button disabled={busy} onClick={()=>run("add_source",[BigInt(orgId),source.label,source.url,source.purpose])} className="rounded-full border border-[#E9E1CF44] px-4 py-3 text-xs disabled:opacity-40">Register source</button><input aria-label="successor manifesto URL" value={manifesto} onChange={e=>setManifesto(e.target.value)} placeholder="https://candidate.example/manifesto" className="border-b border-[#E9E1CF44] bg-transparent p-3 text-xs md:col-span-2"/><button disabled={busy} onClick={()=>run("nominate_successor",[BigInt(orgId),address??"",manifesto])} className="rounded-full border border-[#E9E1CF44] px-4 py-3 text-xs disabled:opacity-40">Nominate connected steward</button><button disabled={busy} onClick={()=>run("seal_organization",[BigInt(orgId)])} className="rounded-full border border-[#E9E1CF44] px-4 py-3 text-xs disabled:opacity-40">Seal charter</button></div><p className="mono mt-4 break-words text-[10px] text-[#B8FF5A]">{state}</p></div>
}

export function VaultActions({orgId}:{orgId:string}){const {address,writeClient,chainOk}=useWallet();const [state,setState]=useState("");const [memo,setMemo]=useState("");const [amount,setAmount]=useState("1");const [busy,setBusy]=useState(false);const release=async()=>{if(busy)return;try{assertConfigured();if(!chainOk)throw new Error("WRONG_NETWORK: switch wallet to Studionet 61999");if(!address||!writeClient)throw new Error("Connect a wallet before signing.");if(!/^0x[0-9a-fA-F]{64}$/.test(memo))throw new Error("Memo must be a bytes32 hash.");setBusy(true);setState("AWAITING_SIGNATURE");await writeClient.connect("studionet");const hash=await writeClient.writeContract({address:env.vaultAddress as `0x${string}`,functionName:"release",args:[BigInt(orgId),address,BigInt(amount),memo]});setState(`CONSENSUS ${hash}`);const final=await confirmWrite(writeClient,hash,async()=>setState(`FINALIZED ${hash} / rereading Vault`));setState(final.hash?`${final.stage} ${final.hash}`:final.stage)}catch(e){setState(e instanceof Error?e.message:"CONTRACT_ERROR")}finally{setBusy(false)}};return <div className="mt-5 grid gap-3"><input aria-label="release amount" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="numeric" className="border-b border-[#E9E1CF44] bg-transparent p-3 text-xs" placeholder="Amount in wei"/><input aria-label="release memo hash" value={memo} onChange={e=>setMemo(e.target.value)} className="border-b border-[#E9E1CF44] bg-transparent p-3 text-xs" placeholder="0x + 64 hex memo hash"/><button disabled={busy} onClick={release} className="rounded-full border border-[#E9E1CF44] px-5 py-3 text-xs disabled:opacity-40">Release with current steward permission</button><p className="mono break-words text-[10px] text-[#B8FF5A]">{state}</p></div>}
