import {readCandidates,readOrganization} from "../../../../lib/genlayer/reads";
import {SuccessorActions} from "../../../../components/successor-actions";
export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function Successors({params}:{params:Promise<{id:string}>}){
  const {id}=await params;let org;let candidates=[];let error="";
  try{org=await readOrganization(id);candidates=await readCandidates(id,Number(org.candidate_count))}catch(e){error=e instanceof Error?e.message:"Core read failed"}
  return <div className="mx-auto min-h-screen max-w-4xl px-6 pb-24 pt-36"><p className="mono text-xs tracking-[.3em] text-[#B8FF5A]">FOLIO 03 / SUCCESSORS / {id}</p><h1 className="serif mt-4 text-6xl">Stewardship is self-nominated.</h1>{org&&<div className="mt-6 border-l border-[#B8784E] pl-5"><p className="mono text-[10px] text-[#777269]">SEALED SUCCESSION CRITERIA</p><p className="mt-2 text-sm leading-7">{String(org.succession_criteria??"—")}</p></div>}{error?<p className="mt-10 text-sm text-[#B8784E]">{error}</p>:<div className="mt-10 space-y-4">{candidates.length===0?<p className="border border-[#E9E1CF22] p-6 text-sm text-[#777269]">No candidates are registered in Core.</p>:candidates.map((candidate:{candidate_id:number,candidate:string,manifesto_url:string,active:boolean,latest_outcome:string})=><div key={candidate.candidate_id} className="border border-[#E9E1CF22] p-6"><p className="mono text-xs text-[#B8FF5A]">CANDIDATE {candidate.candidate_id}</p><p className="mono mt-3 break-all text-xs">{candidate.candidate}</p><a className="mt-3 block break-all text-sm underline" href={candidate.manifesto_url} target="_blank" rel="noreferrer">{candidate.manifesto_url}</a><p className="mono mt-4 text-[10px] text-[#777269]">ACTIVE: {String(candidate.active)} / OUTCOME: {candidate.latest_outcome}</p><SuccessorActions orgId={id} candidateId={candidate.candidate_id} candidate={candidate.candidate} active={candidate.active}/></div>)}</div>}</div>;
}
